env: standard

runtime: nodejs16

entrypoint: npm run start:prod

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: automatic
  max_instances: 2
  min_idle_instances: automatic
  max_idle_instances: 1
  max_concurrent_requests: 80
  min_pending_latency: 3000ms
