name: Deploy to Google AppEngine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Google AppEngine

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Create dot env file
        shell: bash
        run: |
          touch .env.production
          echo "FRONT_URL=${{ secrets.FRONT_URL }} >> .env.production
          echo "MONGODB_KEY=${{ secrets.MONGODB_KEY }} >> .env.production
          echo "GRAPHQL_SECRET_KEY=${{ secrets.GRAPHQL_SECRET_KEY }} >> .env.production
          echo "AUTH_SECRET_KEY=${{ secrets.AUTH_SECRET_KEY }} >> .env.production
          echo "ICON_SECRET_KEY=${{ secrets.ICON_SECRET_KEY }} >> .env.production
          echo "MARKDOWN_SECRET_KEY=${{ secrets.MARKDOWN_SECRET_KEY }} >> .env.production
          echo "MAIL_SECRET_KEY=${{ secrets.MAIL_SECRET_KEY }} >> .env.production
          echo "ADMIN_NAME=${{ secrets.ADMIN_NAME }} >> .env.production
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} >> .env.production
          echo "MAIL_USER=${{ secrets.MAIL_USER }} >> .env.production
          echo "MAIL_PASS=${{ secrets.MAIL_PASS }} >> .env.production
          echo "GH_OWNER=${{ secrets.GH_OWNER }} >> .env.production
          echo "GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }} >> .env.production
          echo "TWITTER_AUTH=${{ secrets.TWITTER_AUTH }} >> .env.production

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Nest.js application
        run: |
          npm i
          npm run build

      - name: Setup gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v0'
