name: Deploy to Google AppEngine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Google AppEngine

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Nest.js application
        run: |
          npm i
          npm run build
      
      - name: Generate Twemoji as a json file
        run: node dist/generateTwemoji.js

      - name: Setup gcloud
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy App to GAE
        run: gcloud app deploy --quiet
